# Generated by Django 5.1.1 on 2025-07-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brightness',
            field=models.IntegerField(default=128),
        ),
    ]
